version: '3.8'

services:

  api:
    container_name: laravel-app
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
      - laravel-dependencies:/var/www/html/vendor
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    networks:
      - laravel-network

  web:
    container_name: vue-app
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    volumes:
      - ./vue-app:/app
      - vue-dependencies:/app/node_modules
    ports:
      - "8081:8080"  # Map Vue.js app's port 8080 to host port 8081
    networks:
      - laravel-network

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myproject
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9015:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
  laravel-dependencies:
  vue-dependencies:
